function generateLeviLLZ(GPSpoints, date, imgtime)
%generateLeviLLZ: Create survey data for the GPS points.  Generate a local
%reference coordinate system & arrange Lon/Lat and time in the required
%format for PickControlPointV5 software.
%{
Inputs:
    - GPSpoints =   [table] Table generated by importing iG8 data from the
                     Landstar phone app.  See importGPSpoints.m
    - date      =   [yyyyMMdd](string) date of img capture
    - imgtime   =   [datetime vector] Spoofed data of img capture times.
                    GPS shots are recorded a few seconds after.
%}
%% Input Parsing
p= inputParser;
checkTableFields = @(tbl) istable(tbl) && all(ismember({'Longitude', 'Latitude', 'Elevation'}, tbl.Properties.VariableNames));
validDate = @(x) datetime(capturedate,'Format','yyyyMMdd')==x;
validimgtime =  @(x, GPSpoints) isdatetime(x) && isvector(x) && numel(x) == numel(GPSpoints);

addRequired(p, 'GPSpoints',checkTableFields);
addRequired(p, 'date',validDate);
addRequired(p, 'imgtime',validDate);


parse(p,GPSpoints,imgtime,date);
%% Generate Data
wgs84 = wgs84Ellipsoid; % Define ellipsoid
origin = [GPSpoints.Latitude(1),GPSpoints.Longitude(1),GPSpoints.Elevation(1)]; % Set first point as origin
% Convert lat, lon to local coordinate system
[local.xEast,local.yNorth,local.zUp] = geodetic2enu(GPSpoints.Latitude,GPSpoints.Longitude,GPSpoints.Elevation,origin(1),origin(2),origin(3),wgs84);

%% Create the text file
filename=strcat(date,'Survey.txt');
fid=fopen(fullfile(path,filename),'w');
fprintf(fid,'Year \t Month \t Day \t Hour \t Min \t Sec \t Lat \t Lon \t X \t Y \t Z',size(GPSpoints,1));
for i=1:size(GPSpoints,1)
    % Follow the header above to print the time (using imgtime) and add the
    % Lat / Lon as well as the local.xEast ... etc


    % fprintf(fid, '\n%d) ',GPSpoints{i,1});
    % fprintf(fid, '%.0s ',datatable{i,2});
     fprintf(fid, '%s',string(datetime(GPSpoints{i,2},"Format",'MM/dd/yyyy HH:mm:ss:mss')));
end
fclose(fid);

fprintf('Success! File has been created here: %s\n',fullfile(path,filename))

end