function generateLeviLLZ(GPSpoints, date, filename)
%generateLeviLLZ: Create survey data for the GPS points.  Generate a local
%reference coordinate system & arrange Lon/Lat and time in the required
%format for PickControlPointV5 software.
%   GPSpoints =   [table] Table generated by importing iG8 data from the
%                 Landstar phone app.  See importGPSpoints.m
%   date    =   [yyyyMMdd](string) date of img capture

%% Input Parsing
p= inputParser;
checkTableFields = @(tbl) istable(tbl) && all(ismember({'Longitude', 'Latitude', 'Elevation'}, tbl.Properties.VariableNames));
validDate = @(x) datetime(capturedate,'Format','yyyyMMdd')==x;

addRequired(p, 'GPSpoints',checkTableFields);
addRequired(p, 'date',validDate);

parse(p,GPSpoints,date);
%% Generate Data
wgs84 = wgs84Ellipsoid; % Define ellipsoid
origin = [GPSpoints.Latitude(1),GPSpoints.Longitude(1),GPSpoints.Elevation(1)]; % Set first point as origin
% Convert lat, lon to local coordinate system
[local.xEast,local.yNorth,local.zUp] = geodetic2enu(GPSpoints.Latitude,GPSpoints.Longitude,GPSpoints.Elevation,origin(1),origin(2),origin(3),wgs84);

%% Create the text file
filename=strcat(date,'Survey.txt');
fid=fopen(fullfile(path,filename),'w');
fprintf(fid,'# of Frames: %d',size(datatable,1));
for i=1:size(datatable,1)
    fprintf(fid, '\n%d) ',datatable{i,1});
    % fprintf(fid, '%.0s ',datatable{i,2});
    fprintf(fid, '%s',string(datetime(datatable{i,2},"Format",'MM/dd/yyyy HH:mm:ss:mss')));
end
fclose(fid);

fprintf('Success! File has been created here: %s\n',fullfile(path,filename))

end